[package]
name = "blockchain"
version = "0.1.0"
authors = ["logan"]

[dependencies]
blake2 = "0.6.1"
crypto-mac = "0.4.0"
ed25519-dalek = "0.4.2"
generic-array = "0.8.2"
rand = "0.3.16"
time = "0.1.38"